#!/bin/bash
#
# Licensing:
#
# Copyright © Laurence Lumi 2017
# Licensed GNU General Public License v3
# which can be found here https://www.gnu.org/licenses/gpl-3.0.en.html
#

convert -colorspace LAB \
-size 300x100 canvas:"cielab(100%,0,0)" \
-size 300x100 canvas:"cielab(96%,0,0)" \
-size 300x100 canvas:"cielab(92%,0,0)" \
-size 300x100 canvas:"cielab(88%,0,0)" \
-size 300x100 canvas:"cielab(84%,0,0)" \
-size 300x100 canvas:"cielab(80%,0,0)" \
-size 300x100 canvas:"cielab(76%,0,0)" \
-size 300x100 canvas:"cielab(72%,0,0)" \
-size 300x100 canvas:"cielab(68%,0,0)" \
-size 300x100 canvas:"cielab(64%,0,0)" \
-size 300x100 canvas:"cielab(60%,0,0)" \
-size 300x100 canvas:"cielab(56%,0,0)" \
-size 300x100 canvas:"cielab(52%,0,0)" \
-size 300x100 canvas:"cielab(48%,0,0)" \
-size 300x100 canvas:"cielab(44%,0,0)" \
-size 300x100 canvas:"cielab(40%,0,0)" \
-size 300x100 canvas:"cielab(36%,0,0)" \
-size 300x100 canvas:"cielab(32%,0,0)" \
-size 300x100 canvas:"cielab(28%,0,0)" \
-size 300x100 canvas:"cielab(20%,0,0)" \
-size 300x100 canvas:"cielab(16%,0,0)" \
-size 300x100 canvas:"cielab(12%,0,0)" \
-size 300x100 canvas:"cielab(8%,0,0)" \
-size 300x100 canvas:"cielab(4%,0,0)" \
-size 300x100 canvas:"cielab(1%,0,0)" \
-append -colorspace sRGB sRGBstepwedge.tif
#-append -colorspace sRGB sRGBstepwedge.tif
