#!/bin/bash
#
# Licensing:
#
# Copyright © Laurence Lumi 2017
# Licensed GNU General Public License v3
# which can be found here https://www.gnu.org/licenses/gpl-3.0.en.html
#

progname=`basename $0`
usage()
	{
	echo >&2 ""
	echo >&2 "$progname:" "$@"
        cat << MESSAGE1
USAGE: $progname infile [outfile_prefix]
USAGE: takepicture [-h or -help]

OPTIONS:

MESSAGE1
exit 1
	}
help()
{
    echo >&2 ""
    echo >&2 "$progname:" "$@"
    cat  >&2 << MESSAGE2

NAME: takepicture

PURPOSE: digital simulation of film negative for testing purposes, point the camera at jpg and take a picture


Arguments:

MESSAGE2
exit 1
}

tmpdir="./"
tmpprefix=$tmpdir"_tp_"
COMMENT="Processed with takepicture"
M_GAMMA=1.625 #ISO film gamma
R_GAMMA=1.807 #Portra 400 as default
G_GAMMA=1.817 #Portra 400 as default
B_GAMMA=1.563 #Portra 400 as default
B_POINT=0.005 #not sure what do with this
PROF_DIR=$HOME/.scantools
zip="-compress zip"
approach="c_invert_then_BP_then_gamma"
showtmp=0

while [ $# -gt 0 ]
do
    # get parameters
    case "$1" in
        -h|-help)    # help information
            echo ""
            help
            ;;
        -)    # STDIN and end of arguments
            break
            ;;
        -*)    # any other - argument
            echo "--- UNKNOWN OPTION ---"
            usage
            ;;
        *)     # end of arguments
            break
            ;;
    esac
    shift   # next option
done

infile=$1
outfile=$2

if [ -z $infile ]; then
    echo "must provide a filename"
    usage
fi
if [ ! -f "$infile" -o ! -r "$infile" ]; then
    echo "Cannot open: $infile"
    exit 1
fi

if [ -z $outfile ]; then
    outfile=`basename ${infile%".jpg"}-P.tif`
fi
tmpfileprefix="$tmpprefix"`basename "${outfile%.tif}"`
DEBUG echo tmpfileprefix: $tmpfileprefix
DEBUG echo outprefix: $outprefix


#step to a linear capture

convert $infile -depth 16 -fx "Fy=((u)*100+16)/116;delta=6/29;Fy>delta?Fy^3:(Fy-16/116)3*delta^2" -type TrueColor "$tmpfileprefix"_linear_cap.tif

#next invert

Jn_MIN=0.015

#convert "$tmpfileprefix"_linear_cap.tif -strip $CSPACE  \
#     +channel -fx " (u-$BP)/(1-$BP)" \
#    -set comment "$COMMENT" "$tmpfileprefix"_BP.tif


convert "$tmpfileprefix"_linear_cap.tif -strip \
    -channel R -fx "Fx=log(u/(1/128));10^-(.15+(Fx>0?.5534*Fx:0))" \
    -channel G -fx "Fx=log(u/(1/128));10^-(.7+(Fx>0?.5534*Fx:0))" \
    -channel B -fx "Fx=log(u/(1/128));10^-(.8+(Fx>0?.6384*Fx:0))" \
    -set comment "$COMMENT" "$tmpfileprefix"_inverted_only.tif

convert "$tmpfileprefix"_inverted_only.tif -set colorspace RGB -colorspace sRGB -set comment "$COMMENT" $outfile

exit 0
