#!/bin/bash
convert -size 300x300 canvas:gray"(18%)" 18per.tif
convert -size 300x300 canvas:gray"(50%)" 50per.tif

convert 50per.tif -set colorspace RGB -separate \( -clone 0 -poly "1,1" \) -swap 0,3 -delete 3 \( -clone 1 -poly "1,1" \) -swap 1,3 -delete 3 \( -clone 2 -poly "1,1" \) -swap 2,3 -delete 3 -set colorspace RGB -combine -type TrueColor 1.tif

convert 50per.tif 2.tif

convert 50per.tif -set colorspace RGB -separate 1%d.tif


convert 10.tif 11.tif 12.tif -set colorspace RGB -combine 1_.tif
